export const RECEIVE_RESTAURANT = 'RECEIVE_RESTAURANT';
export const REQUEST_RESTAURANT = 'REQUEST_RESTAURANT';
export const ERROR_RECEIVE_RESTAURANT = 'ERROR_RECEIVE_RESTAURANT';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';