export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';
export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS';
export const ERROR_RECEIVE_RESTAURANTS = 'ERROR_RECEIVE_RESTAURANTS';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const ERROR_DELETE_RESTAURANT = 'ERROR_DELETE_RESTAURANT';